export const timeSaleData = { //时段销售
	"columns": [{
		"field": "time_xi",
		"title": "时段"
	}, {
		"field": "sale_amount",
		"title": "销额增量"
	}, {
		"field": "total_sale_amount",
		"title": "销额累计"
	}, {
		"field": "last_sale_amount",
		"title": "销额增量"
	}, {
		"field": "last_total_sale_amount",
		"title": "销额累计"
	}],
	"data": [{
		"time_xi": 9,
		"sale_amount": "4,732",
		"total_sale_amount": "4,732",
		"last_sale_amount": "31,746",
		"last_total_sale_amount": "31,746"
	}, {
		"time_xi": 10,
		"sale_amount": "60,148",
		"total_sale_amount": "64,880",
		"last_sale_amount": "969",
		"last_total_sale_amount": "32,715"
	}, {
		"time_xi": 11,
		"sale_amount": "1,249",
		"total_sale_amount": "66,129",
		"last_sale_amount": "1,099",
		"last_total_sale_amount": "33,814"
	}, {
		"time_xi": 12,
		"sale_amount": "-",
		"total_sale_amount": "66,129",
		"last_sale_amount": "18,707",
		"last_total_sale_amount": "52,521"
	}, {
		"time_xi": 13,
		"sale_amount": "14,175",
		"total_sale_amount": "80,304",
		"last_sale_amount": "14,878",
		"last_total_sale_amount": "67,399"
	}, {
		"time_xi": 14,
		"sale_amount": "27,097",
		"total_sale_amount": "107,401",
		"last_sale_amount": "12,376",
		"last_total_sale_amount": "79,775"
	}, {
		"time_xi": 15,
		"sale_amount": "38,588",
		"total_sale_amount": "145,989",
		"last_sale_amount": "12,452",
		"last_total_sale_amount": "92,227"
	}, {
		"time_xi": 16,
		"sale_amount": "-",
		"total_sale_amount": "145,989",
		"last_sale_amount": "13,919",
		"last_total_sale_amount": "106,146"
	}, {
		"time_xi": 17,
		"sale_amount": "9,637",
		"total_sale_amount": "155,626",
		"last_sale_amount": "7,874",
		"last_total_sale_amount": "114,020"
	}, {
		"time_xi": 18,
		"sale_amount": "-2,748",
		"total_sale_amount": "152,878",
		"last_sale_amount": "10,842",
		"last_total_sale_amount": "124,862"
	}, {
		"time_xi": 19,
		"sale_amount": "-",
		"total_sale_amount": "152,878",
		"last_sale_amount": "8,496",
		"last_total_sale_amount": "133,358"
	}, {
		"time_xi": 20,
		"sale_amount": "-",
		"total_sale_amount": "152,878",
		"last_sale_amount": "1,208",
		"last_total_sale_amount": "134,566"
	}, {
		"time_xi": 21,
		"sale_amount": "-969",
		"total_sale_amount": "151,909",
		"last_sale_amount": "-",
		"last_total_sale_amount": "134,566"
	}, {
		"time_xi": 22,
		"sale_amount": "-",
		"total_sale_amount": "151,909",
		"last_sale_amount": "-",
		"last_total_sale_amount": "134,566"
	}]
}

export const sexSaleData = {  //性别销售
	"columns": [{
		"field": "genderName",
		"title": "类别"
	}, {
		"field": "sale_quantity",
		"title": "销量"
	}, {
		"field": "sale_amount",
		"title": "销售额"
	}, {
		"field": "sale_discount",
		"title": "折扣"
	}, {
		"field": "same_store_ratio",
		"title": "同店同比"
	}, {
		"field": "sale_amount_ratio",
		"title": "销额%"
	}, {
		"field": "inventory_amount_ratio",
		"title": "存额%"
	}, {
		"field": "inventory_quantity",
		"title": "库存量"
	}, {
		"field": "inventory_amount",
		"title": "库存额"
	}, {
		"field": "last_sale_quantity",
		"title": "同期销量"
	}, {
		"field": "last_sale_amount",
		"title": "同期销额"
	}, {
		"field": "last_inventory_quantity",
		"title": "同期存量"
	}, {
		"field": "last_inventory_amount",
		"title": "同期存额"
	}, {
		"field": "last_sale_amount_ratio",
		"title": "同期销额%"
	}, {
		"field": "last_inventory_amount_ratio",
		"title": "同期存额%"
	}, {
		"field": "last_sale_discount",
		"title": "同期折扣"
	}],
	"data": [{
		"genderName": "34124321412341234213412342134213421342134",
		"sale_quantity": "211",
		"sale_amount": "151,909,121,111",
		"sale_discount": "99.0%",
		"same_store_ratio": "-12.1%",
		"sale_amount_ratio": "100.0%",
		"inventory_amount_ratio": "100.0%",
		"inventory_quantity": "12,176",
		"inventory_amount": "8,742,914",
		"last_sale_quantity": "231",
		"last_sale_amount": "172,830",
		"last_sale_discount": "98.3%",
		"last_inventory_quantity": "0",
		"last_inventory_amount": "0",
		"last_sale_amount_ratio": "10000000.0%",
		"last_inventory_amount_ratio": "-"
	}, {
		"genderName": "男子男子男子男子男子",
		"sale_quantity": "82",
		"sale_amount": "70,596",
		"sale_discount": "99.8%",
		"same_store_ratio": "-19.7%",
		"sale_amount_ratio": "46.5%",
		"inventory_amount_ratio": "53.8%",
		"inventory_quantity": "5,849",
		"inventory_amount": "4,704,981",
		"last_sale_quantity": "94",
		"last_sale_amount": "87,925",
		"last_sale_discount": "98.6%",
		"last_inventory_quantity": "0",
		"last_inventory_amount": "0",
		"last_sale_amount_ratio": "50.9%",
		"last_inventory_amount_ratio": "-"
	}, {
		"genderName": "女子",
		"sale_quantity": "50",
		"sale_amount": "38,630",
		"sale_discount": "100.0%",
		"same_store_ratio": "-28.9%",
		"sale_amount_ratio": "25.4%",
		"inventory_amount_ratio": "25.2%",
		"inventory_quantity": "2,847",
		"inventory_amount": "2,200,163",
		"last_sale_quantity": "67",
		"last_sale_amount": "54,343",
		"last_sale_discount": "100.0%",
		"last_inventory_quantity": "0",
		"last_inventory_amount": "0",
		"last_sale_amount_ratio": "31.4%",
		"last_inventory_amount_ratio": "-"
	}, {
		"genderName": "中性",
		"sale_quantity": "9",
		"sale_amount": "2,761",
		"sale_discount": "100.0%",
		"same_store_ratio": "110.8%",
		"sale_amount_ratio": "1.8%",
		"inventory_amount_ratio": "6.3%",
		"inventory_quantity": "1,207",
		"inventory_amount": "550,513",
		"last_sale_quantity": "10",
		"last_sale_amount": "1,310",
		"last_sale_discount": "100.0%",
		"last_inventory_quantity": "0",
		"last_inventory_amount": "0",
		"last_sale_amount_ratio": "0.8%",
		"last_inventory_amount_ratio": "-"
	}, {
		"genderName": "儿童儿童儿童儿童儿童儿童儿童儿童儿童",
		"sale_quantity": "70",
		"sale_amount": "39,922",
		"sale_discount": "96.5%",
		"same_store_ratio": "36.5%",
		"sale_amount_ratio": "26.3%",
		"inventory_amount_ratio": "14.7%",
		"inventory_quantity": "2,273",
		"inventory_amount": "1,287,257",
		"last_sale_quantity": "60",
		"last_sale_amount": "29,252",
		"last_sale_discount": "94.3%",
		"last_inventory_quantity": "0",
		"last_inventory_amount": "0",
		"last_sale_amount_ratio": "16.9%",
		"last_inventory_amount_ratio": "-"
	}]
} //性别销售

export const areaSaleData = { //区域销售
	"columns": [{
		"field": "area_sale",
		"title": "楼层"
	}, {
		"field": "block_name",
		"title": "区域"
	}, {
		"field": "sale_amount",
		"title": "销售金额"
	}, {
		"field": "sale_quantity",
		"title": "销量"
	}, {
		"field": "sale_amount_ratio",
		"title": "销额%"
	}, {
		"field": "aur",
		"title": "AUR"
	}],
	"data": [{
		"area_sale": "总计",
		"mergecell_num": 1,
		"aur": "729",
		"sale_amount": "151,532",
		"sale_quantity": "208",
		"block_name": "-",
		"sale_amount_ratio": "100000000.0%"
	}, {
		"area_sale": "一层",
		"mergecell_num": 8,
		"aur": "656",
		"sale_amount": "87,182",
		"sale_quantity": "133",
		"block_name": "一层合计",
		"sale_amount_ratio": "57.5%"
	}, {
		"area_sale": "一层",
		"mergecell_num": null,
		"aur": "652",
		"sale_amount": "5,212",
		"sale_quantity": "8",
		"block_name": "女跑",
		"sale_amount_ratio": "3.4%"
	}, {
		"area_sale": "一层",
		"mergecell_num": null,
		"aur": "397",
		"sale_amount": "3,970",
		"sale_quantity": "10",
		"block_name": "女训",
		"sale_amount_ratio": "2.6%"
	}, {
		"area_sale": "一层",
		"mergecell_num": null,
		"aur": "913",
		"sale_amount": "29,218",
		"sale_quantity": "32",
		"block_name": "女休",
		"sale_amount_ratio": "19.3%"
	}, {
		"area_sale": "一层",
		"mergecell_num": null,
		"aur": "806",
		"sale_amount": "8,057",
		"sale_quantity": "10",
		"block_name": "男跑",
		"sale_amount_ratio": "5.3%"
	}, {
		"area_sale": "一层",
		"mergecell_num": null,
		"aur": "457",
		"sale_amount": "3,199",
		"sale_quantity": "7",
		"block_name": "男训",
		"sale_amount_ratio": "2.1%"
	}, {
		"area_sale": "一层",
		"mergecell_num": null,
		"aur": "569",
		"sale_amount": "37,526",
		"sale_quantity": "66",
		"block_name": "儿童",
		"sale_amount_ratio": "24.8%"
	}, {
		"area_sale": "一层",
		"mergecell_num": null,
		"aur": "0",
		"sale_amount": "0",
		"sale_quantity": "0",
		"block_name": "足球",
		"sale_amount_ratio": "0.0%"
	}, {
		"area_sale": "M层",
		"mergecell_num": 4,
		"aur": "858",
		"sale_amount": "64,350",
		"sale_quantity": "75",
		"block_name": "M层合计",
		"sale_amount_ratio": "42.5%"
	}, {
		"area_sale": "M层",
		"mergecell_num": null,
		"aur": "825",
		"sale_amount": "11,555",
		"sale_quantity": "14",
		"block_name": "篮球",
		"sale_amount_ratio": "7.6%"
	}, {
		"area_sale": "M层",
		"mergecell_num": null,
		"aur": "942",
		"sale_amount": "23,555",
		"sale_quantity": "25",
		"block_name": "乔丹",
		"sale_amount_ratio": "15.5%"
	}, {
		"area_sale": "M层",
		"mergecell_num": null,
		"aur": "812",
		"sale_amount": "29,240",
		"sale_quantity": "36",
		"block_name": "男子生活",
		"sale_amount_ratio": "19.3%"
	}]
}

export const activitySaleData = { //活动区域
	"columns": [{
		"field": "sale_time_activity",
		"title": "时间"
	}, {
		"field": "activity_name",
		"title": "活动",
        "styles": {fontWeight: 'bold', color: '#867ae4', textAlign: 'left'},
		"theadStyles": {textAlign: 'left'},
	}, {
		"field": "discount",
		"title": "折扣"
	}, {
		"field": "sale_amount",
		"title": "销售额"
	}, {
		"field": "sale_amount_ratio",
		"title": "销额%"
	}, {
		"field": "sale_quantity",
		"title": "销售量"
	}, {
		"field": "shoes_sale_amount",
		"title": "鞋销额"
	}, {
		"field": "shoes_sale_quantity",
		"title": "鞋销量"
	}, {
		"field": "clothes_sale_amount",
		"title": "服销额"
	}, {
		"field": "clothes_sale_quantity",
		"title": "服销量"
	}, {
		"field": "accessory_sale_amount",
		"title": "配销额"
	}, {
		"field": "accessory_sale_quantity",
		"title": "配销量"
	}],
	"data": [{
		"sale_time_activity": "本期本期本期本期本期本期本期本期本期本期本期本期本期本期 2019/01/20",
		"sale_time_activity_mergecell_num": 6,
		"activity_name": "全部",
		"discount": "99.0%",
		"sale_amount": "151,909",
		"sale_amount_ratio": "100.0%",
		"sale_quantity": "211",
		"shoes_sale_amount": "89,062",
		"shoes_sale_quantity": "105",
		"clothes_sale_amount": "59,838",
		"clothes_sale_quantity": "95",
		"accessory_sale_amount": "3,009",
		"accessory_sale_quantity": "11",
        "styles": {fontWeight: 'bold', color: 'red', textAlign: 'left'},
        // "important": true,
	}, {
		"sale_time_activity": "本期 2019/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "无活动",
		"discount": "100.0%",
		"sale_amount": "2,647",
		"sale_amount_ratio": "1.7%",
		"sale_quantity": "3",
		"shoes_sale_amount": "2,647",
		"shoes_sale_quantity": "3",
		"clothes_sale_amount": "0",
		"clothes_sale_quantity": "0",
		"accessory_sale_amount": "0",
		"accessory_sale_quantity": "0",
        "activity_name_jump_func": function(index, indexs, item, vm) {
            console.log(index);
            console.log(indexs);
            console.log(item);
            console.log(vm);
        }
	}, {
		"sale_time_activity": "本期 2019/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "正价",
		"discount": "100.0%",
		"sale_amount": "131,307",
		"sale_amount_ratio": "86.4%",
		"sale_quantity": "183",
		"shoes_sale_amount": "75,891",
		"shoes_sale_quantity": "89",
		"clothes_sale_amount": "52,407",
		"clothes_sale_quantity": "83",
		"accessory_sale_amount": "3,009",
		"accessory_sale_quantity": "11",
	}, {
		"sale_time_activity": "本期 2019/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "正价|会员积分抵现（金/黑卡）-华北一",
		"discount": "98.3%",
		"sale_amount": "16,017",
		"sale_amount_ratio": "10.5%",
		"sale_quantity": "21",
		"shoes_sale_amount": "10,524",
		"shoes_sale_quantity": "13",
		"clothes_sale_amount": "5,493",
		"clothes_sale_quantity": "8",
		"accessory_sale_amount": "0",
		"accessory_sale_quantity": "0"
	}, {
		"sale_time_activity": "本期 2019/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "海带7折",
		"discount": "70.2%",
		"sale_amount": "560",
		"sale_amount_ratio": "0.4%",
		"sale_quantity": "2",
		"shoes_sale_amount": "0",
		"shoes_sale_quantity": "0",
		"clothes_sale_amount": "560",
		"clothes_sale_quantity": "2",
		"accessory_sale_amount": "0",
		"accessory_sale_quantity": "0"
	}, {
		"sale_time_activity": "本期 2019/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "海带返利",
		"discount": "57.5%",
		"sale_amount": "1,378",
		"sale_amount_ratio": "0.9%",
		"sale_quantity": "2",
		"shoes_sale_amount": "0",
		"shoes_sale_quantity": "0",
		"clothes_sale_amount": "1,378",
		"clothes_sale_quantity": "2",
		"accessory_sale_amount": "0",
		"accessory_sale_quantity": "0"
	}, {
		"sale_time_activity": "同期 2018/01/20",
		"sale_time_activity_mergecell_num": 4,
		"activity_name": "全部",
		"discount": "98.3%",
		"sale_amount": "172,830",
		"sale_amount_ratio": "100.0%",
		"sale_quantity": "231",
		"shoes_sale_amount": "116,565",
		"shoes_sale_quantity": "115",
		"clothes_sale_amount": "54,651",
		"clothes_sale_quantity": "100",
		"accessory_sale_amount": "1,614",
		"accessory_sale_quantity": "16",
        "styles": {fontWeight: 'bold', color: 'red'},
        "important": true,
	}, {
		"sale_time_activity": "同期 2018/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "无活动",
		"discount": "77.7%",
		"sale_amount": "8,732",
		"sale_amount_ratio": "5.1%",
		"sale_quantity": "19",
		"shoes_sale_amount": "2,228",
		"shoes_sale_quantity": "2",
		"clothes_sale_amount": "6,504",
		"clothes_sale_quantity": "17",
		"accessory_sale_amount": "0",
		"accessory_sale_quantity": "0",
        // "styles": {fontWeight: 'bold', color: 'red'},
        // "important": true,
	}, {
		"sale_time_activity": "同期 2018/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "儿童棉羽5折",
		"discount": "49.9%",
		"sale_amount": "499",
		"sale_amount_ratio": "0.3%",
		"sale_quantity": "1",
		"shoes_sale_amount": "0",
		"shoes_sale_quantity": "0",
		"clothes_sale_amount": "499",
		"clothes_sale_quantity": "1",
		"accessory_sale_amount": "0",
		"accessory_sale_quantity": "0",
        "activity_name_jump_func": function(index, indexs, item, vm) {
            console.log(index);
            console.log(indexs);
            console.log(item);
            console.log(vm);
        }
	}, {
		"sale_time_activity": "同期 2018/01/20",
		"sale_time_activity_mergecell_num": null,
		"activity_name": "正价",
		"discount": "100.0%",
		"sale_amount": "163,599",
		"sale_amount_ratio": "94.7%",
		"sale_quantity": "211",
		"shoes_sale_amount": "114,337",
		"shoes_sale_quantity": "113",
		"clothes_sale_amount": "47,648",
		"clothes_sale_quantity": "82",
		"accessory_sale_amount": "1,614",
		"accessory_sale_quantity": "16"
	}]
}
